# Generated by Django 4.0.6 on 2023-03-06 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('managertool', '0003_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
