# Generated by Django 4.0.6 on 2023-03-11 07:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managertool', '0005_project_author_remove_project_executors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='executors',
            field=models.ManyToManyField(null=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
