# Generated by Django 4.0.6 on 2023-03-11 08:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('managertool', '0006_alter_project_executors'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='executors',
            field=models.ManyToManyField(blank=True, related_name='participants', to=settings.AUTH_USER_MODEL),
        ),
    ]
